---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: gitops-secret
 namespace: vplugindemo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: gitops-secret-binding
 namespace: vplugindemo
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
 kind: Role
 name: openshift-gitops-secret
 apiGroup: rbac.authorization.k8s.io
